### ISSUE TITLE
TypeError in register_vote_and_proxy_votes()

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-voting#100]
- create 3 users (A, B, C)
- Edit A and add B and C to field 'proxy'
- Now start named electronic voting of a motion
- Login as A
- Try to send a vote for motion
=> Server Error:
```
  File "openslides_voting/voting.py", line 186, in _register_vote_and_proxy_votes
    self._register_vote_and_proxy_votes(vote, proxy.delegate, result_token)
TypeError: _register_vote_and_proxy_votes() missing 1 required positional argument: 'result_token'
```

**Comment by emanuelschuetze** [comment]
I get this error also with VoteCollector tests. It would be helpful to fix this asap.
@jwinzer or @FinnStutzenstein Can somebody look at this error?

**Comment by jwinzer** [comment]
Line 186 needs to be:
self._register_vote_and_proxy_votes(vote, proxy.delegate, **device**, result_token)

**Comment by FinnStutzenstein** [comment]
Please add this in #97 .

**Comment by emanuelschuetze** [comment]
Done in #97
