### ISSUE TITLE
Only provide allowed voting methods in poll dialog

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-voting#103]
Show only allowd voting types in poll dialog and hide types which cannot used for electronic voting.
Currently the "start voting" button is missing - and there is no hint that this type is not supported.

E.g. all "votecollector" voting types cannot be used for election method 'YN' or for elections with more than one open posts.

**Comment by FinnStutzenstein** [comment]
> E.g. all "votecollector" voting types cannot be used for election method 'YN' or for elections with more than one open posts.
I think this is the only case. All electronic voting modes support every poll method. Just the VC is restrictive in the given case: YN(A) with >1 candidate.
I'll create a PR.
