### ISSUE TITLE
Named voting does not work if config "Enable proxies and absentee votes" is active

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-voting#105]
- create new delegate user A
- activate config "Enable proxies and absentee votes"
- start named voting for a motion
- log in as A
=> no possibility to vote for motion!

- deactivate config "Enable proxies and absentee votes"
- restart named voting as admin
- log in as A
=> now voting is possible

**Comment by jwinzer** [comment]
@emanuelschuetze I'm unable to reproduce the problem.

**Comment by emanuelschuetze** [comment]
Strange, I cannot reproduce it too. So closed.
