### ISSUE TITLE
VoteCollector with absentee vote: one vote is missing

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-voting#109]
User VoteCollector poll type with VoteCollector simulator:
- Activate config "Enable proxies and absentee votes" and "Enable VoteCollector"
- add User A, B and C
- set A and B as present
- add Keypad 1 and 2 for A and B
- edit A: add C as proxy user
- add new absentee vote for C (e.g. vote with N for motion 1)
- create VoteCollector poll for motion 1.
- start voting
=> 2/2 votes (expected: 3 votes!)
- open single votes table -> 2 votes: User B (ok), User C (absentee vote, ok).
=> vote of User A is missing!
 
 @jwinzer Can you confirm this?

**Comment by jwinzer** [comment]
This works as designed. C is not an active proxy for A since C is not present.

**Comment by emanuelschuetze** [comment]
@jwinzer As discussed I can confim it. But there is an other problem in the following setup:

- user A and B are present and have keypad 1 and 2
- user C is represented by user A (add A as proxy user to C), C is not present and without keypad!
- add an absentee vote vor C
- now start voting
=> 3/4(!) votes are displayed -> Why 4? 3 expected.
