### ISSUE TITLE
Illegal keypad responses by the votecollector

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-voting#11]
The votecolltector is started with all keypads, whose users are present. This set of keypads is in the most cases too large: One user, and two keypads, one assigned to the user -> both keypads are found.

So the votecollector simulator sends results for both keypads. In a real scenario, one can grab the not assigned keypad and vote. We should restrict the list of keypads [here](https://github.com/OpenSlides/openslides-voting/blob/master/openslides_voting/votecollector/rpc.py#L74) by just taking all keypads that are assigned to `authorized_voters`.

I need info about the things going on in the `rpc.start_voting`. What are the `options`, what arguments does `votecollector.prepare_voting()` take?

**Comment by jwinzer** [comment]
By purpose all keypads whose users are present were allowed to cast votes.

Validation was done in Ballot.register_vote thru admitted_delegates. [admitted_delegates](https://github.com/OpenSlides/openslides-voting/blob/ff33e830a0fe41385cc0d781721ae12945b4bcb2/openslides_voting/voting.py#L189)

You eliminated that code which might cause additional problems. Let's discuss this on the phone.

**Comment by jwinzer** [comment]
Oh, I see that authorization is now handled by the new model AuthorizedVoters.

For all voting modes except for Ping (system test) we could restrict keypads to the ones assigned to authorized_voters. However, we should not raise a ValidationError [here](https://github.com/OpenSlides/openslides-voting/blob/master/openslides_voting/votecollector/views.py#L274) but replace is with continue.

**Comment by FinnStutzenstein** [comment]
Current state: We do not restrict keypads. For the votecollector named voting, the keypads are restricted through their assigned users. For anonymous voting, every registered keypad can vote.
