### ISSUE TITLE
VoteCollector: Abstain votes are not submitted

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-voting#134]
Try to send an abstain vote for an assignment vote (e.g. 2 candidates, 1 open post). Key '0' was counted by VoteCollector but it was not enterd in voting form (field abstain is 0).

Maybe something in the validate_candidate_votes function is wrong?
https://github.com/OpenSlides/openslides-voting/blob/master/openslides_voting/votecollector/views.py#L313

@jwinzer Can you check it please?

**Comment by jwinzer** [comment]
Fixed with PR #135

**Comment by emanuelschuetze** [comment]
Done
