### ISSUE TITLE
Resolve TODOs in voting.py

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-voting#4]
There are two important todos: Line 137 and 190. I cannot test them, becuase I need a simulator for the VoteCollector. Please find another way to get the `VotingPrincipal` that **may** be associated with `motion`. Maybe there is something like `principals_set`, which just can have zero or one element. THis is ensured [here](https://github.com/OpenSlides/openslides-voting/blob/master/openslides_voting/models.py#L24).

**Comment by jwinzer** [comment]
I think you should implement principals_set. In Windows search for "VoteCollector" and you will find an app "VoteCollector (Simulatorversion)" that you can use to simulate keypad entries.
