### ISSUE TITLE
Projector needs dictionary of admitted delegates to draw the delegates table

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/openslides-voting#48]
Original design:
The projector shows a delegate board while voting is active. In order to know which delegates to show the projector got a dictionary (key: keypad number, value: list of user_id) via a [GET request.](https://github.com/OpenSlides/openslides-voting/blob/ff33e830a0fe41385cc0d781721ae12945b4bcb2/openslides_voting/static/js/openslides_voting/projector.js#L116)

[AdmittedDelegatesView](https://github.com/OpenSlides/openslides-voting/blob/ff33e830a0fe41385cc0d781721ae12945b4bcb2/openslides_voting/views.py#L139)
[get_admitted_delegates](https://github.com/OpenSlides/openslides-voting/blob/ff33e830a0fe41385cc0d781721ae12945b4bcb2/openslides_voting/voting.py#L35)

This code has been removed. Let's discuss how to handle this. Do we want to use a RESTView instead?

**Comment by FinnStutzenstein** [comment]
As discussed:
- Ids of all admitted delegates are saved in autorized voters models
- the projector should get all users (this has to be restricted later) and the authorized voter model
- for all votes the client should find the authorized voter (Implement the `find_authorized_voter` on the client)
- implement your delegate board -- I'll ad the oldstyle seating plan later with a config to change between both
