### ISSUE TITLE
Allow voters to participate late in the game

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/openslides-voting#53]
We need to decide if we allow voters to be added to the list of authorized voters or deleted from the list while voting is ALREADY active. I tend to say No.

[post_save signal](https://github.com/OpenSlides/openslides-voting/blob/master/openslides_voting/apps.py#L84)

[update_authorized_voters](https://github.com/OpenSlides/openslides-voting/blob/master/openslides_voting/signals.py#L26)

**Comment by FinnStutzenstein** [comment]
Yes, this is my opinion, too. THis makes the voting more transparent -- you cannot add or remove someone silently.

**Comment by emanuelschuetze** [comment]
> We need to decide if we allow voters to be added to the list of authorized voters or deleted from the list 
> while voting is ALREADY active.

No! – @jwinzer This is the current state right? So we can close this issue?

**Comment by jwinzer** [comment]
The current state is NO. Please remove the TODO and commented lines before closing.
[post_save signal](https://github.com/OpenSlides/openslides-voting/blob/master/openslides_voting/apps.py#L84)
