### ISSUE TITLE
ImproperlyConfigured

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/openslides-voting#58]
ImproperlyConfigured is raised when creating an assignment.

![image](https://user-images.githubusercontent.com/20415092/41585408-48c3d41c-73aa-11e8-99a7-8ae1d3df1c9f.png)

**Comment by FinnStutzenstein** [comment]
I cannot recreate this.. Can you drop your database and look, if this appears again?

**Comment by jwinzer** [comment]
I cannot replicate the problem after dropping the database. Fixed.

**Comment by jwinzer** [comment]
I was wrong. Problem still occurs. It seems to be related to the projector view.

**Comment by FinnStutzenstein** [comment]
Can you provide your database and instructions how to recreate? (E.g. mailing it to me)

**Comment by jwinzer** [comment]
Steps to replicate problem:

1. Open Antrag 1
2. Click "Projezieren"
3. Click 1. Abstimmung bearbeiten
4. Click "Abstimmungsergebnis projezieren"

![image](https://user-images.githubusercontent.com/20415092/41644667-0815d774-746f-11e8-84f2-02bacc36a9bf.png)

**Comment by FinnStutzenstein** [comment]
fixed with #67

**Comment by FinnStutzenstein** [comment]
No, we must not yield them: They are yielded, if the motion is yielded, because the motion is the root rest element.

**Comment by jwinzer** [comment]
Aha, I see. You're right. I need to watch the motion:

![image](https://user-images.githubusercontent.com/20415092/42224594-caa36084-7eda-11e8-83e8-84bd184b2826.png)

**Comment by FinnStutzenstein** [comment]
No, you can just watch for the motionpoll. This should work, because it is an own model in the client.

**Comment by jwinzer** [comment]
The debugger cannot find the motionpoll.

![image](https://user-images.githubusercontent.com/20415092/42225535-0a8c7594-7edd-11e8-90b2-69d4b4ce0ef0.png)
