### ISSUE TITLE
No error message

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/openslides-voting#63]
If you edit a participant and assign a keypad that is already assigned to another participant the error alert is shown but no error message.

![image](https://user-images.githubusercontent.com/20415092/42155353-7e51d41a-7de8-11e8-8c77-5f84d2cc9cb3.png)

**Comment by FinnStutzenstein** [comment]
Funny ;)
Do you want to look at it, or shall I do it tomorrow?

**Comment by jwinzer** [comment]
Please assign to yourself.
