### ISSUE TITLE
Delegate board requires publishing first

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/openslides-voting#71]
When you create a _**new**_ assignment poll and start voting the delegate board is not shown when clicking "Project election result". Why? Because it requires the poll to be published first. This means that you have to close the ballot form, click "Publish" and then"Enter votes" to restart voting. This is awkward behaviour and should be simplified.

![image](https://user-images.githubusercontent.com/20415092/43323013-b1f17452-91b0-11e8-8210-fb5df10cd9cc.png)

**Comment by FinnStutzenstein** [comment]
Maybe we add the publish button to the form, so one must not close it.

**Comment by jwinzer** [comment]
I don't like the idea of an extra button. How about if clicking "Project election result" will activate "publish"?
