### ISSUE TITLE
Which title to use for motions and assignments

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/openslides-voting#73]
@FinnStutzenstein What is the difference between assignment.agenda_item.getTitle() and assignment.title? When does it make sense to use {{ assignment.agenda_item.getTitle() || and assignment.title }} in templates? The same applies to motions.

**Comment by FinnStutzenstein** [comment]
the `getTitle()` from an `Agenda_item` may be a different as a from the object itself. Mostyl shorter and a more common sense for the agenda. we should use this for the voting plugin.
the special case with `|| assignment.title` I don't know, maybe this is a relict of the past, we should use just the `getTiele()`.
