### ISSUE TITLE
Alert message not shown on "Edit participant"

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/openslides-voting#74]
There is no error message visible when the form does not validate, e.g. bad email:

![image](https://user-images.githubusercontent.com/20415092/43417208-ab0b647c-943a-11e8-926b-28caf6a23ed5.png)

**Comment by emanuelschuetze** [comment]
Cannot reproduce this with bad email. I get a error message.
@jwinzer Please retest.

**Comment by jwinzer** [comment]
I can no longer reproduce this. I'm getting an error message now.
