### ISSUE TITLE
Assignment poll form does not open

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/openslides-voting#81]
When you create a new ballot for either named electronic or VoteCollector voting you get
TypeError: Cannot read property 'options' of undefined
and the poll form does not open immediately. You have to click "Ballot x" again to open the form.

**Comment by FinnStutzenstein** [comment]
Does this always happens?

**Comment by jwinzer** [comment]
Yes, have you tried it?

**Comment by FinnStutzenstein** [comment]
Yes, it works for me.. I cannot reproduce this.

**Comment by jwinzer** [comment]
It always happens to me. This is the same issues as [64](https://github.com/OpenSlides/openslides-voting/issues/64)

**Comment by FinnStutzenstein** [comment]
closed because of duplicate #64
