### ISSUE TITLE
Adding a proxy user gets error "Voting principles and shares are not enabled."

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-voting#99]
- Enable proxies and absentee votes
- open edit user dialog
- add a new user to "proxy" field
- save
=> "Error: Voting principles and shares are not enabled."

**Comment by jwinzer** [comment]
Yes, I agree. "Enable voting shares" should not depend on "Enable VoteCollector". Voting shares can be used with any type of electronic voting.

**Comment by emanuelschuetze** [comment]
But it should also possible to use proxies _without_ voting shares, right?

**Comment by jwinzer** [comment]
Yes, of course but I don't know of any use case yet. Finn and I decided to only have one config setting to enable both.

**Comment by FinnStutzenstein** [comment]
Your described behavior isn't reproducible here.. Enabling proxies and absentee votes (just one checkbox in the settings) is (and should be) enough.

**Comment by emanuelschuetze** [comment]
Works for me now with current master and new database.
